name: Build & Package Dev, Cut Pre-Release
on:
  push:
    branches: 
      - development
    tags:
      # Only run workflow on tags with the format x.y.z-dev
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Git describe
        id: ghd
        uses: proudust/gh-describe@v1
      # Configure to pull internal Packages, then Yarn Install
      - name: Setup NodeJS for NPMJS Build Step 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name : Prep Release Zip
        shell: bash
        run: |
          mv paver-${{steps.ghd.outputs.describe}}.zip bin/
          cp LICENSE bin/
          cp README.md bin/
          cp helpers bin/ -r
          cp config.example.json bin/config.example.json
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: bin/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/paver-${{steps.ghd.outputs.describe}}.zip
            bin/config.example.json
            bin/helpers
            LICENSE
            README.md
          generate_release_notes: true
